const axios = require('axios');
require('dotenv').config();

const openAiEndpoint = process.env.OPENAI_ENDPOINT;
const apiKey = process.env.OPENAI_API_KEY;
const deploymentName = process.env.OPENAI_DEPLOYMENT_NAME;

const generateTags = async (title, image) => {
  const messages = [
    {
      role: "system",
      content: "당신은 주어진 제목과 이미지를 기반으로 추억 카드의 태그를 생성하는 도움을 주는 AI입니다. 답변으로는 태그만 제공해야 합니다. 예를 들어 가족과 함께 여행을 갔던 바다 사진이 제공될 경우, '가족, 여행, 바다'와 같은 태그를 생성해주세요. 그 외에도 사진에 관한 다양한 태그를, 3~4개 정도 생성해주세요. 또한 태그의 글자 수를 모두 합쳤을 때 10글자 이하여야 합니다."
    },
    {
      role: "user",
      content: `제목: "${title}" 이 이미지에 대한 태그를 생성해주세요: ${image}`
    }
  ];

  const params = {
    messages: messages,
    max_tokens: 50,
    temperature: 0.7
  };

  try {
    const response = await axios.post(`${openAiEndpoint}/openai/deployments/${deploymentName}/chat/completions?api-version=2024-07-01-preview`, params, {
      headers: {
        "api-key": apiKey,
        "Content-Type": "application/json"
      }
    });

    if (response.data.choices && response.data.choices.length > 0) {
      const tags = response.data.choices[0].message.content.split(',').map(tag => tag.trim());
      return tags;
    } else {
      throw new Error("No tags generated by AI.");
    }
  } catch (error) {
    console.error("Error in generateTags:", error);
    throw error;
  }
};

module.exports = {
  generateTags
};
